version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "com.h2database:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.puppycrawl.tools:checkstyle"
        update-types: ["version-update:semver-major"]
      - dependency-name: "io.ratpack:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jakarta.*:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jakarta.servlet:jakarta.servlet-api"
      - dependency-name: "javax:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "javax.servlet:servlet-api"
        versions: [">= 2.4"]
      - dependency-name: "org.apache.groovy:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.codehaus.groovy:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.eclipse.persistence:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.gebish:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.hibernate:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.jooq:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.junit.jupiter:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.junit.platform:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.seleniumhq.selenium:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.seleniumhq.selenium:selenium-api"
        versions: [">= 4.35, < 5"]
      - dependency-name: "org.seleniumhq.selenium:selenium-firefox-driver"
        versions: [">= 4.35, < 5"]
      - dependency-name: "org.seleniumhq.selenium:selenium-support"
        versions: [">= 4.35, < 5"]
      - dependency-name: "org.spockframework:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework:*"
        update-types: ["version-update:semver-major"]
