sudo: false
language: java
jdk:
  - openjdk8
addons:
  firefox: "68.8.0esr"
branches:
  only:
  - master
  - /^travis-.*/
dist: xenial
services:
  - xvfb
before_install:
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz"
  - "mkdir geckodriver"
  - "tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver"
  - "export PATH=$PATH:$PWD/geckodriver"
install: ./gradlew clean resolveAllDependencies
script: ./gradlew -Dscan assemble check uploadSnapshots
env:
  global:
  - TERM=dumb
  - ORG_GRADLE_PROJECT_enableBuildScans=true
  - secure: "JUvsQdNlTT5HO3FX+3A4Ex/V9kiiGQe9yYU9IxkrN6ohyYLCwbNn32cdFC3PUsqV+FYEbSGU2lGnEWtfysWZEehFZZb15DhV/6LlpO4XMec2QWbbD2DaW6NKmHC8GEo1dXDqJTZRBz9mMWSojZvCnScLjn3UIT3krJbgdUlrJPE="
  - secure: "MXVhVp0m2IHaAb905jKfN44I+qI8vB3Vix6QdX4gGecDaOUG4kcUXlDBbvUeW9mlGo1nQYT+fyimZmMpAOQRoKbQnqcNWUegzexH8iqk5X+mq/9SrWx7vLS8N9uyJWCctECRb7BpB7xjBo7jFQa5UcA3qIo1ngR+Rt2e3PXZo4w="
