name: "Build Gradle project"
on: [ workflow_call ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: |
              8
              11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v0.0.0
        with:
          firefox-version: 128.10.0esr

      - name: Setup Geckodriver
        uses: browser-actions/setup-geckodriver@v0.0.0
        with:
          geckodriver-version: 0.36.0

      - name: Build
        run: ./gradlew assemble

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: ./gradlew check --continue
