name: "Build, test and publish snapshots"
on:
  push:
    branches:
      - main

jobs:
  call-gradle-build:
    uses: tomdcc/miniprofiler-jvm/.github/workflows/gradle-build.yml@main
  call-publish-snapshots:
    needs: call-gradle-build
    uses: tomdcc/miniprofiler-jvm/.github/workflows/gradle-publish-snapshots.yml@main
    secrets: inherit
