name: "Build, test and publish snapshots"
on:
  push:
    branches:
      - master

jobs:
  call-gradle-build:
    uses: tomdcc/miniprofiler-jvm/.github/workflows/gradle-build.yml@master
  call-publish-snapshots:
    uses: tomdcc/miniprofiler-jvm/.github/workflows/gradle-publish-snapshots.yml@master
